stages:
  - test
#  - build
#  - test image
#  - deploy

image: docker:latest

services:
  - docker:dind

test:
  stage: test
  image: $MONK_DOCKER_PRECOMPILED
  cache:
    key: $CI_PIPELINE_ID
    paths:
      - /go/src
      - /go/pkg
    policy: push
  services:
    - 'postgres:latest'
  script:
    - for i in $(printenv | cut -d '=' -f 1); do ENV_WORD=$(echo $i | cut -d '_' -f 1); if [ "$ENV_WORD" = "TEST" ]; then export ${i/TEST_/}="${!i}"; fi; done
    - make protocomplile
    - go get
    - make test
  variables:
    POSTGRES_USER: $TEST_POSTGRES_USER
    POSTGRES_PASSWORD: $TEST_POSTGRES_PASSWORD